// EXIF field categories and their associated field names
export const exifCategories = {
  basic: [
    'ExifTool Version Number',
    'File Name',
    'Directory',
    'File Size',
    'File Type',
    'File Type Extension',
    'MIME Type',
    'Major Brand',
    'Minor Version',
    'Compatible Brands',
  ],
  camera: [
    'Make',
    'Camera Model Name',
    'Model',
    'Software',
    'Serial Number',
    'Internal Serial Number',
    'Fuji Model',
    'Camera Elevation Angle',
    'Roll Angle',
  ],
  exposure: [
    'Exposure Time',
    'F Number',
    'ISO',
    'Exposure Program',
    'Exposure Compensation',
    'Exposure Mode',
    'Metering Mode',
    'Shutter Speed Value',
    'Aperture Value',
    'Brightness Value',
    'Max Aperture Value',
    'Exposure Warning',
    'Auto Bracketing',
  ],
  lens: [
    'Lens Info',
    'Lens Make',
    'Lens Model',
    'Lens Serial Number',
    'Focal Length',
    'Focal Length In 35mm Format',
    'Min Focal Length',
    'Max Focal Length',
    'Max Aperture At Min Focal',
    'Max Aperture At Max Focal',
    'Lens Modulation Optimizer',
    'Lens ID',
  ],
  focus: [
    'Focus Mode',
    'AF Mode',
    'Focus Pixel',
    'AF-S Priority',
    'AF-C Priority',
    'Focus Mode 2',
    'Pre AF',
    'AF Area Mode',
    'AF Area Point Size',
    'AF Area Zone Size',
    'AF-C Setting',
    'AF-C Tracking Sensitivity',
    'AF-C Speed Tracking Sensitivity',
    'AF-C Zone Area Switching',
    'Focus Warning',
    'Subject Distance Range',
  ],
  flash: [
    'Flash',
    'Light Source',
    'Fuji Flash Mode',
    'Flash Exposure Comp',
    'Flash Metering Mode',
    'Slow Sync',
    'Flicker Reduction',
  ],
  datetime: [
    'Date/Time Original',
    'Create Date',
    'Modify Date',
    'File Modification Date/Time',
    'File Access Date/Time',
    'File Inode Change Date/Time',
    'Offset Time',
    'Offset Time Original',
    'Offset Time Digitized',
    'GPS Date/Time',
    'GPS Time Stamp',
    'GPS Date Stamp',
  ],
  gps: [
    'GPS Version ID',
    'GPS Latitude',
    'GPS Latitude Ref',
    'GPS Longitude',
    'GPS Longitude Ref',
    'GPS Altitude',
    'GPS Altitude Ref',
    'GPS Position',
    'GPS Speed',
    'GPS Speed Ref',
    'GPS Time Stamp',
    'GPS Date Stamp',
    'GPS Date/Time',
  ],
  imageProperties: [
    'Image Width',
    'Image Height',
    'Image Size',
    'Meta Image Size',
    'Exif Image Width',
    'Exif Image Height',
    'Image Spatial Extent',
    'Orientation',
    'X Resolution',
    'Y Resolution',
    'Resolution Unit',
    'Bits Per Sample',
    'Megapixels',
    'Aspect Ratio',
    'Color Space',
    'Color Profiles',
    'Color Primaries',
    'Matrix Coefficients',
  ],
  whiteBalance: [
    'White Balance',
    'White Balance Fine Tune',
    'White Balance Bias',
    'WB Shift AB',
    'WB Shift GM',
    'Color Temperature',
    'Auto White Balance',
    'Standard White Balance GRB',
  ],
  fuji: [
    'Film Mode',
    'Dynamic Range',
    'Dynamic Range Setting',
    'Auto Dynamic Range',
    'Highlight Tone',
    'Shadow Tone',
    'Saturation',
    'Sharpness',
    'Noise Reduction',
    'Clarity',
    'Grain Effect Roughness',
    'Grain Effect Size',
    'Color Chrome Effect',
    'Color Chrome FX Blue',
    'Picture Mode',
    'Quality',
    'Contrast',
    'Image Generation',
    'Image Count',
    'Exposure Count',
  ],
  technical: [
    'Sensing Method',
    'File Source',
    'Scene Type',
    'Scene Capture Type',
    'Custom Rendered',
    'Focal Plane X Resolution',
    'Focal Plane Y Resolution',
    'Focal Plane Resolution Unit',
    'Image Stabilization',
    'Blur Warning',
    'Shutter Type',
    'Drive Mode',
    'Drive Speed',
    'Sequence Number',
    'Scale Factor To 35 mm Equivalent',
    'Circle Of Confusion',
    'Field Of View',
    'Hyperfocal Distance',
    'Light Value',
  ],
  video: [
    'HEVC Configuration Version',
    'General Profile Space',
    'General Tier Flag',
    'General Profile IDC',
    'Gen Profile Compatibility Flags',
    'Constraint Indicator Flags',
    'General Level IDC',
    'Min Spatial Segmentation IDC',
    'Parallelism Type',
    'Chroma Format',
    'Bit Depth Luma',
    'Bit Depth Chroma',
    'Average Frame Rate',
    'Constant Frame Rate',
    'Num Temporal Layers',
    'Temporal ID Nested',
    'Transfer Characteristics',
    'Video Full Range Flag',
    'Image Pixel Depth',
    'Rotation',
    'Media Data Size',
    'Media Data Offset',
  ],
  faceDetection: ['Faces Detected', 'Num Face Elements', 'Face Detection'],
  other: [
    'File Permissions',
    'Handler Type',
    'Primary Item Reference',
    'Other Image',
    'Preview Image',
    'Thumbnail Image',
    'Exif Byte Order',
    'Y Cb Cr Positioning',
    'Copyright',
    'Components Configuration',
    'Compressed Bits Per Pixel',
    'Version',
    'Flashpix Version',
    'Interoperability Index',
    'Interoperability Version',
    'Composite Image',
    'PrintIM Version',
    'Artist',
    'Rating',
    'User Comment',
  ],
} as const
